### ISSUE TITLE
Error when running example_tiny_ophys_training.py

### ISSUE THREAD

**Issue by bumoritz** [AllenInstitute/deepinterpolation#17]
Hello! 

Thanks a lot for making this package available, looks really exciting and super useful!

I am planning to apply DeepInterpolation to my 2P imaging data and am currently working through your example scripts. When running example_tiny_ophys_training.py, I get the following error.

Interestingly, the example_tiny_ephys_training.py script runs without a problem. Furthermore, we have installed the package on a different computer and the ophys training did work there, even though we installed it in exactly the same way. 

It may be difficult to troubleshoot that from far, but I thought maybe you have an idea what could cause the error. Thanks a lot in advance for your help!

...
`2021-02-17 11:56:21.533099: I tensorflow/core/common_runtime/bfc_allocator.cc:1034] 1 Chunks of size 251658240 totalling 240.00MiB
2021-02-17 11:56:21.533532: I tensorflow/core/common_runtime/bfc_allocator.cc:1034] 1 Chunks of size 314572800 totalling 300.00MiB
2021-02-17 11:56:21.533968: I tensorflow/core/common_runtime/bfc_allocator.cc:1034] 2 Chunks of size 335544320 totalling 640.00MiB
2021-02-17 11:56:21.534432: I tensorflow/core/common_runtime/bfc_allocator.cc:1034] 1 Chunks of size 503316480 totalling 480.00MiB
2021-02-17 11:56:21.536130: I tensorflow/core/common_runtime/bfc_allocator.cc:1034] 2 Chunks of size 1006632960 totalling 1.88GiB
2021-02-17 11:56:21.539742: I tensorflow/core/common_runtime/bfc_allocator.cc:1038] Sum Total of in-use chunks: 4.62GiB
2021-02-17 11:56:21.540275: I tensorflow/core/common_runtime/bfc_allocator.cc:1040] total_region_allocated_bytes_: 7050928896 memory_limit_: 7050929120 available bytes: 224 curr_region_allocation_bytes_: 14101858304
2021-02-17 11:56:21.540831: I tensorflow/core/common_runtime/bfc_allocator.cc:1046] Stats:
Limit:                      7050929120
InUse:                      4960237568
MaxInUse:                   5342113792
NumAllocs:                         377
MaxAllocSize:               3528507392
Reserved:                            0
PeakReserved:                        0
LargestFreeBlock:                    0

2021-02-17 11:56:21.541334: W tensorflow/core/common_runtime/bfc_allocator.cc:439] ***************************_************_________*****____******************************____________
2021-02-17 11:56:21.541790: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at conv_grad_input_ops.cc:1103 : Resource exhausted: OOM when allocating tensor with shape[5,192,512,512] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
2021-02-17 11:56:21.633124: W tensorflow/core/common_runtime/bfc_allocator.cc:246] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.83GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
Traceback (most recent call last):
  File "example_tiny_ophys_training.py", line 148, in <module>
    training_class.run()
  File "C:\Users\Moritz\Anaconda3\envs\DI\lib\site-packages\deepinterpolation-0.1.2-py3.8.egg\deepinterpolation\trainor_collection.py", line 204, in run
  File "C:\Users\Moritz\Anaconda3\envs\DI\lib\site-packages\tensorflow\python\keras\engine\training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)
  File "C:\Users\Moritz\Anaconda3\envs\DI\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1098, in fit
    tmp_logs = train_function(iterator)
  File "C:\Users\Moritz\Anaconda3\envs\DI\lib\site-packages\tensorflow\python\eager\def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "C:\Users\Moritz\Anaconda3\envs\DI\lib\site-packages\tensorflow\python\eager\def_function.py", line 840, in _call
    return self._stateless_fn(*args, **kwds)
  File "C:\Users\Moritz\Anaconda3\envs\DI\lib\site-packages\tensorflow\python\eager\function.py", line 2829, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "C:\Users\Moritz\Anaconda3\envs\DI\lib\site-packages\tensorflow\python\eager\function.py", line 1843, in _filtered_call
    return self._call_flat(
  File "C:\Users\Moritz\Anaconda3\envs\DI\lib\site-packages\tensorflow\python\eager\function.py", line 1923, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "C:\Users\Moritz\Anaconda3\envs\DI\lib\site-packages\tensorflow\python\eager\function.py", line 545, in call
    outputs = execute.execute(
  File "C:\Users\Moritz\Anaconda3\envs\DI\lib\site-packages\tensorflow\python\eager\execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.ResourceExhaustedError:  OOM when allocating tensor with shape[5,192,512,512] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[node gradient_tape/functional_1/conv2d_8/Conv2D/Conv2DBackpropInput (defined at C:\Users\Moritz\Anaconda3\envs\DI\lib\site-packages\deepinterpolation-0.1.2-py3.8.egg\deepinterpolation\trainor_collection.py:204) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
 [Op:__inference_train_function_1782]

Function call stack:
train_function

2021-02-17 11:56:22.094538: W tensorflow/core/kernels/data/generator_dataset_op.cc:103] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.
         [[{{node PyFunc}}]]`

**Comment by jeromelecoq** [comment]
Hi, 

I am glad you are trying this out. From this error, it seems like this is a memory error. Your GPU does not have enough GPU RAM to support this training set of parameters. You could either reduce the batch size or use a GPU with larger GPU RAM. 

Keep in mind that smaller batch sizes will tend to converge slower and in some cases less accurately.

**Comment by bumoritz** [comment]
Thanks a lot for your quick reply! 

The GPU RAM was indeed a very helpful hint. There is an option in the NVIDIA control panel (we're using an NVIDIA Quadro P400 with 8 GB) called 'Manage GPU Utilization, Usage Mode'. After changing it from 'Use for Graphics and compute needs' to 'Dedicate to graphics tasks', the ophys training script was running without an error. Thanks a lot, again!

**Comment by jeromelecoq** [comment]
Oh that is a new one to me! Thanks for sharing your fix
